name: Deploy to GitHub Packages
on:
  workflow_dispatch:
  push:
    branches:
      - maven-central
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
          
      - name: Publish Package -lib-bumblebee
        run: mvn -DskipTests -Dgpg.skip=true -DPublishing.skip=true -B package

      - name: Publish package to github Repo
        run: mvn -DskipTests -Dgpg.skip=true -DPublishing.skip=true -B clean deploy --settings .github/workflows/github-settings.xml
        env:
          LIB_GITHUB_ACTOR: '${{ secrets.LIB_GITHUB_ACTOR }}'
          LIB_GITHUB_TOKEN: '${{ secrets.LIB_GITHUB_TOKEN }}'